apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bsky-secret-external
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: vault-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: bsky-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: opaque
      data:
        BSKY_PASSWORD: "{{ .bsky_password }}"
  data:
  - secretKey: bsky_password
    remoteRef:
      key: secret/bluesky
      property: BSKY_PASSWORD